name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-build:
    name: Building laravel
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clear cache
      run: php artisan cache:clear
    - name: Run build
      run: npm run prod
